- name: Check Installed Packages
  become: yes
  package_facts:
    manager: auto

- name: Install Curl
  become: yes
  package:
    name: curl
    state: present
    use: auto

- name: Install Docker Repo If Docker Not Present (Rocky)
  become: yes
  shell: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: '"Rocky" in hostvars[inventory_hostname].ansible_distribution'

- name: Install Docker If Not Present
  become: yes
  ansible.builtin.shell: curl -LJ get.docker.com | sh
  when: ("Rocky" not in hostvars[inventory_hostname].ansible_distribution) and
        ("docker-ce" not in ansible_facts.packages)

- name: Remove podman
  become: yes
  #ignore_unreachable: true
  package:
    name:
      - cockpit-podman
      - podman
      - podman-catatonit
      - perl-podlators
      - containers-common
      - buildah
    state: absent
  when: '"Rocky" in hostvars[inventory_hostname].ansible_distribution'

- name: Update Docker (requires latest)
  become: yes
  #ignore_unreachable: true
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-ce-rootless-extras
      - docker-compose-plugin
      - docker-buildx-plugin
    state: latest

- name: Start Docker Service
  become: yes
  service:
    name: docker
    state: "started"
    enabled: true
