- name: Install MySQL on Ubuntu and set up accounts
  hosts: sqlhost
  remote_user: ansible
  become: true
  become_method: sudo
  vars:
    ansible_ssh_pass: ansible
    ansible_become_pass: ansible
    key_values:
      - 'b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAonYqNhe5BXPkFWXryuXLGWqFkD5grYZmNmlFY09vyRsrEEREV8+i
MSbSpS+FlHj3aCiScnTpObDXbgReJS1+exzMmZbmO2foADG5x8IniCw4IctSNqE3YFBiYg
Rf1DQlKituhvCn2muDB+rzZB9mdQJ302qcaZNYKyESspExxr2eVCoDv+ij6Vz8zHR1QnLo
De6j0bHpSyN8XRATgYHEKTUfe6O/hOLb+JOyudTyT0899TJXCRZFJe6aHR3/CNn0yb7sMe
jtMni/p2TpM5F/w+S8YYqOARPYTu1pwgWG5EVscHSoXdhmBLlgR8B4d/0ZphQpeGic3avc
k3JvLyoTESBlkqyXLNFMy7t0eVunJjy8pzbaOTLqiYxEWOsKroN5llWVRniTbua3HmPolt
tgeBMMSGwo4ADp4xKU+LrD8P5DUEMd3d4YOpwKPHeIkR+0AbwfEkrgeWhp8BJbq1KKnaxW
nauCq+Pi2yTt00Bdt61QKpO4Y4X+cgGi41gQf87U9BXPwb8WCiM/m8kzlosdHx042MYEs7
4QQx1ECD70cfzzhd9yNthZfZ1alNVXh2G4EZA3gMLgI+KjvIgu4UPF8viszMaetvVZSWLX
C7mz+s3TKSJOjr03KR3T7vyEmgVhmBbVRBeREBhnZYV3qaecguHAjcnZFyMlEhNykun7oB
kAAAdAEEhYQxBIWEMAAAAHc3NoLXJzYQAAAgEAonYqNhe5BXPkFWXryuXLGWqFkD5grYZm
NmlFY09vyRsrEEREV8+iMSbSpS+FlHj3aCiScnTpObDXbgReJS1+exzMmZbmO2foADG5x8
IniCw4IctSNqE3YFBiYgRf1DQlKituhvCn2muDB+rzZB9mdQJ302qcaZNYKyESspExxr2e
VCoDv+ij6Vz8zHR1QnLoDe6j0bHpSyN8XRATgYHEKTUfe6O/hOLb+JOyudTyT0899TJXCR
ZFJe6aHR3/CNn0yb7sMejtMni/p2TpM5F/w+S8YYqOARPYTu1pwgWG5EVscHSoXdhmBLlg
R8B4d/0ZphQpeGic3avck3JvLyoTESBlkqyXLNFMy7t0eVunJjy8pzbaOTLqiYxEWOsKro
N5llWVRniTbua3HmPolttgeBMMSGwo4ADp4xKU+LrD8P5DUEMd3d4YOpwKPHeIkR+0Abwf
EkrgeWhp8BJbq1KKnaxWnauCq+Pi2yTt00Bdt61QKpO4Y4X+cgGi41gQf87U9BXPwb8WCi
M/m8kzlosdHx042MYEs74QQx1ECD70cfzzhd9yNthZfZ1alNVXh2G4EZA3gMLgI+KjvIgu
4UPF8viszMaetvVZSWLXC7mz+s3TKSJOjr03KR3T7vyEmgVhmBbVRBeREBhnZYV3qaecgu
HAjcnZFyMlEhNykun7oBkAAAADAQABAAACABAM6hMxiU1FW5eUm/TN+qCOclcjnoQORuth
v6H132aoOTswb2sYf57pBb8doI4gXFsNRRirPb5+Hu6G3nFAWyJZIEqdSq48UAKy5vaaEz
NEISCPmJX+m/y3PF0QLxKFO1W8+Dy7Km4tGIMv/m9aHdJ6FbIMsprInJmYOSNsrlUC91E7
3GZ5mrYLwosFh28y8IOt27/0GocaoKcGF1NAaYujrLJXpWyAyDg5CVuMMwtMWiPvHwOuEF
NUzSOKyt9KP0GuS+ILb+HAZbjpQpPecFe/cbAWUvy+w+xaTsxFJQRI6pN6pwasgjm9wcoc
9RnvprjOfaFgfnz1BYQItnzbpInwkfN1U07m0N5T/kQ2Fzk3ql+zcCVTimI4qV9rKiDN3S
qDOX1ZE0lLNFYj6hQlOmvzEBYywgyS9MPYxIv6EBv6u27ieCZLavkMYomxLm2BdpVPZ8vw
2s353Af93PdV5hmeHfp7CfEtpeeNXSVA3x62unMj4RDV5bopDsi6pdYDkHatBvLiJ3d7YG
DoAq7LZwEeq+kLGEAvBApiX/aJmtUm2fW6UtV5tuh6oH4MPNAoYFo9VvV8hpzQVicgu7vz
R+sZdxVvkOun22Ns9ME22o7NOYoBqSieWeVuZ5ObPeCcv7eFjAQLDd25mfWQzdtpbFXj36
L5hNqvd//UGUxezvStAAABACueymKW5xH9tgsNBYTJvesS5PSoBFMS/FVwFlN0FIupHcFe
YgzSgT85xZP6flWM84/b7q6IOQOvA9QtvmQEsaQGwwGNVGzLIlyCmx9TJH5shOw9kKpOJV
DkTvKDHrFY9bPdC+hhynliYXQ+xfOMtraPImlZn02B0i+eB6zCLrzhz5DG00SOSIdnFwj0
HqNGzUQU1KSAHIg/EH41Gg1M1iWMM18dSbq3UUqhmkLmnilLedXK8eXL4N5n0yFHBbNu62
UC/UbZSxZi375wE/JEFINVDOxSaAUDf1G/7ykZJZwzHSTBwMi4PpWhhjRec+nzJ5E6iUH6
7FsP0imc3ffm06AAAAEBANBMGeiVVCsy6Sw+1VaTzKk8N2+/91GvmoyJZ+vQCfHfIDKMbg
zs3QGb3PvNcOSr5JVZXfjAUlOeOdVBygUC0a/oM/Bd7S1Jy4rfUB125IwFrU+p5ZeNyJUY
0c2NrtxFpLAw7VwbGDu4ZVV9tlQBJeygHEhTTKX+n+yHB3Kea2DsbHypaKeF6aRypk5Tvk
FMKL4tGZJRWqnuyScpLgSna0rTo9wlxxfCb1Py6Bcg5YsKCqIbZJR4HBFSB0aKcthX3atH
SjVYWFjW+X+fxVrEGyTal/mclvvo185MCebgmQ7Q383BDHxrv/+BUqfB829NDnDoi4B0qY
qc05DWJ2GTwAUAAAEBAMeq17xBz2RZKQMXn4SjZ7IZxWUxN/VOrC12W/TMjMlut6LfEgZt
c8bvBLSiKz1jHEs3kOmtW0aAqPOcMynf676gyseQZRu1BaJZOrU4OfM2LqAmUl1RVVZiv4
8l5Dr8A5oteU/VKwkFdFOvd+PgMtPT323BXPAq/nuD1Ua8l9GYTBLnHDWCXLzrsE1pbP+A
lJEKbwIlx8FbyhGwVwmLp4eqfaTR0RVk7HDOUaXVboAo79eTN0aCyNNOqj1ZFYHsLN8oIY
FRJ5zVXuN5xXtdNd8vI+/Ihe8hT92SUA/1KWVWnh7ZxrOxU47iIg7eZeCLqL3X5/zVVM1v
2OSkF3hrYAUAAAAEdGVzdAECAwQFBgc='
      - 'b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAwtYNbRCsvCOfMrAEq/jN3deNIwdBAo3HIV+gyV4uyZbkQw86adLw
xsgnTqx9yNJvxTvA5HYsBFN50oYI0g2yGwNSwQaAZzUU+6Nv7STH5jbH8k927Xhbv4yoVC
FKen7QCwSxYGxRWy98WNZmMRNraV3RStGLBZRmFuL0p56qIz33gO7fwFTS5U7MGSDM9kRe
neA0u/ggd6ObqQR3OzR9PrOa0ZPZWeFgjfJ+6CFfWIR9yNPwoK8UfANxq6v6FyMcCFlYKw
3T853dJhYbhB1uWx519dMPpOMQWuSU0SlmArm4bioBtBBXaagXc0AL+WfRNAM28KbGACQ2
plIPzkC7v5Ix7ICyj8tPvwxqmnJH2Xr5/mjFmNoc2CFQdJUJpvYD0kGFVWTU4W+zk1eSmo
PdfvNG3Th9pRki1cj3TvAhMM3DdeaIevHVDEf8djZVgdNAazFPxEo9Wg1qtIgL5AM6FSq4
G51Nl8pead/Iv0wbn0/898N3Bw54crGgcKWEdiRmNvkdqOFIEVW7vZ5+ISpqbLWuc02PhW
voVsCmkanDIYC8cGwJAfAHVBvRt+ZiVJmzwQOHlLtf+bOpPZTAxNimpMJwpn4zpKuaIEmI
3V3/BHctOA9pal9dFqSNpzayi8nfaH+yT/8ZRQO6M6uX9jC8h2iUGPJgES72eK4m3kuqeY
UAAAdABUVVOgVFVToAAAAHc3NoLXJzYQAAAgEAwtYNbRCsvCOfMrAEq/jN3deNIwdBAo3H
IV+gyV4uyZbkQw86adLwxsgnTqx9yNJvxTvA5HYsBFN50oYI0g2yGwNSwQaAZzUU+6Nv7S
TH5jbH8k927Xhbv4yoVCFKen7QCwSxYGxRWy98WNZmMRNraV3RStGLBZRmFuL0p56qIz33
gO7fwFTS5U7MGSDM9kReneA0u/ggd6ObqQR3OzR9PrOa0ZPZWeFgjfJ+6CFfWIR9yNPwoK
8UfANxq6v6FyMcCFlYKw3T853dJhYbhB1uWx519dMPpOMQWuSU0SlmArm4bioBtBBXaagX
c0AL+WfRNAM28KbGACQ2plIPzkC7v5Ix7ICyj8tPvwxqmnJH2Xr5/mjFmNoc2CFQdJUJpv
YD0kGFVWTU4W+zk1eSmoPdfvNG3Th9pRki1cj3TvAhMM3DdeaIevHVDEf8djZVgdNAazFP
xEo9Wg1qtIgL5AM6FSq4G51Nl8pead/Iv0wbn0/898N3Bw54crGgcKWEdiRmNvkdqOFIEV
W7vZ5+ISpqbLWuc02PhWvoVsCmkanDIYC8cGwJAfAHVBvRt+ZiVJmzwQOHlLtf+bOpPZTA
xNimpMJwpn4zpKuaIEmI3V3/BHctOA9pal9dFqSNpzayi8nfaH+yT/8ZRQO6M6uX9jC8h2
iUGPJgES72eK4m3kuqeYUAAAADAQABAAACAF6clDN4q/DGeYmjKPmbndiS0hIG9T44u9CM
f+cZCa5RzDF2RR7bVJmq20+ceo5ZBfaogBBRBCnroVYmSUU7algswnRCZHr5r2FM6c6mFD
5KLskPZoiFcEQxmRIVgnW+e+dF1Z6lqtIVWpRHNKOzMu8dJENpQtGoUPTfK//zj9oCPtyI
4vWiGzFIFNtE7tLNu4Z9uA3pPVbrh2zJYt7Iq+MVU2JfIeZAB+OWNKMjhYnV+MDbjldw/Y
kFIR9EqXKv1W6GeEab9ecwqxHSHXWH1y1/OrfvUIL40lnY8x0otcUwC4vPcTlP0CrZ+d04
5jer/s57myO8UJ0D+NfGNK+rBp/0Y9Q0uB+bHkwr40FIF9c8fSGDenfCLne3K3WCUJhZYz
JF82RXYtSV6q0BMjMguVYmFR2FdoUBlSTcs4vaSRiEYxzYUYcOAWQPRtkr29dH0Gm874G0
uXaqJ8JfEZnas4PqDQGCJ+5pI4rGezzdfUdugt8rlVKGEh5aPFWPZdzjTvi9VxeFe8PJAO
XKZRSjGIUni1R0wUIMVIRJGQIcJKDoI26oOZo3OIms3x5y7yH7q/6tbWaH0mbiChvqJX+D
HnHKJ/CWE+0iPKUl7nI3XxKL0wF8zF25XEo5jAoQKgI/crMeMEVD1zzdL+l5UiRTxnRKNp
3GzSQGMf8b4U/Xw54HAAABAQDOiEVy/LvYU/JeVy4Vt2e/I0jj3JmZpbynmsyTPdNyKkEf
qBJIcEtC5HUWIxGA5/RduZdT9Zhg61Ub3UVWOmac75Jjp3Lh656963fa49saT7TvW5h/6N
8oWA8S+oto+V0t+vq0Su2zMIrzR9dyYM4FD596dLwJ3KXQ0kyGImFf66U2mc3ffILG6Rkh
/USFyuTJ4zjAuVUKCcO7UrljVCg6Ur0n76pRy7rBR/cATTJbaEzTvoNZrk7jFTQVX0mi7R
XEjKrD/tRDg08EK2/clkc0wRIxjTd1xVpkYOhHnJ+haDvGzVgmY/Pl5CUkuz3xklE47bIH
evNZRDtyjS85QwnnAAABAQDxF2xiuD7trIxh2vny/pMMWgxBKnPJCoHfLBk/oCGpoq/UPT
cEWqYe18W1iudnPzTGRSnYN1H3pxShs+3evrxmS2gJ4adAri1FAiNX1sMuNWNEAYq++Fxn
z5Ycavh5uy+IOWay5RDuXLdvhl4Lgz4ODwkmqOtZy74ueiV/7KoFOKEv/xEm6ZQKHCFqgm
rmIoadR+luEMSIjigkSmg68RNIlpqo5sql3W4eTh0DLPivhpd/SGmWRw9MysSXEwBKRa3W
d9nwcEwsRfzL0S/SRIg11+to/16zWIf86fabMl/amID8RAvqhTcQyUVpsVD9whnVcZtLnx
rfAJiRecMZAlNfAAABAQDO4mNQk6BHhNppqmyvr8t0fXHWjbzD9XrA4Cxj1qZfM8nbH2/t
BuQwIxY6ZF2CzItgx81k5lWjxdRGhfvpFHf0rrEjT+1mllupc5nrz+FtHFyRghaM3WlgdI
4cP91I1Yf+Hjqm3coUWh5f0Sf59GSnYibq7PTgrs8s+sCb9GgvL96GrCRg9+/VW36GpUge
AXRXytYtyGQSAfQJYCNTgTtcWwxppyAYjbXsY8q/5euHJ0yaBHyurCEeTqDKifx9cC5DtQ
um1BRsN7Yu2BtI/fz9dN68oA7BSlTLeUzuXt6jnEOTQBjbw0F20G1ZPGslOXw+8RV9IElO
CKHCUDDdNWGbAAAABHRlc3QBAgMEBQY='

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Secure MySQL installation
      debconf:
        name: mysql-server
        question: mysql-server/root_password
        value: SQLr00tpasswurd22
        vtype: password
      become: true
      
    - name: Install PyMySQL
      apt:
        name: python3-pymysql
        state: present

    - name: Create defined user
      user:
        name: secretservice
        password: "{{'SecuristGovtNA1773' | password_hash('sha512')}}"
        groups: sudo
        shell: /bin/bash
        home: /home/secretservice
        createhome: yes

    - name: Create defined user
      user:
        name: nsa
        password: "{{'SecuristGovtNA1773' | password_hash('sha512')}}"
        groups: sudo
        shell: /bin/bash
        home: /home/nsa
        createhome: yes

    - name: Create defined user
      user:
        name: navy
        password: "{{'SecuristGovtNA1773' | password_hash('sha512')}}"
        shell: /bin/bash
        home: /home/navy
        createhome: yes

    - name: Create defined user
      user:
        name: marines
        password: "{{'SecuristGovtNA1773' | password_hash('sha512')}}"
        shell: /bin/bash
        home: /home/marines
        createhome: yes

    - name: Create defined user
      user:
        name: spaceforce
        password: "{{'SecuristGovtNA1773' | password_hash('sha512')}}"
        shell: /bin/bash
        home: /home/spaceforce
        createhome: yes

    - name: Create a MySQL user
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: root
        login_password: SQLr00tpasswurd22
        name: captain_ghost
        password: $#Bl00d16
        priv: '*.*:ALL'
        host: localhost
        state: present
      become: true

    - name: Create a MySQL database
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: classified
        state: present
 
    - name: Add table
      community.mysql.mysql_query:
        login_host: localhost
        login_user: captain_ghost
        login_password: $#Bl00d16
        login_db: classified
        query: |
          CREATE TABLE `keys` (
            id INT AUTO_INCREMENT PRIMARY KEY,
            sshkey TEXT NOT NULL
          );
      ignore_errors: yes

    - name: Insert data into the table
      ansible.builtin.shell: >
        mysql -u captain_ghost --password='$#Bl00d16' -h localhost --port=3306 --database=classified -e "INSERT INTO \`keys\` (sshkey) VALUES ('{{ item }}');"
      with_items: "{{ key_values }}"
